### ISSUE TITLE
Save that cannot be decompressed. (DEBUG ASSERTION FAILED)

### ISSUE THREAD

**Issue by Synthlight** [WolvenKit/CyberCAT#3]
This save was made in 1.04. The game loads it just fine so I'm pretty sure it's not corrupt.

Basically, I made a new corpo femV to see how the appearance looks in the save. This is a save made literally the first time I get control after the intro dialog / mirror scene ends.

[ManualSave-5.zip](https://github.com/SirBitesalot/CyberCAT/files/5720482/ManualSave-5.zip)

I tried first using `v0.0.3-alpha` and then pulled the source and tried what was latest master at the time: commit 3a4f89d86ec70e66d5efb200bfa8ffde2871f282. Both had the same issue.

```
---- DEBUG ASSERTION FAILED ----
   at CyberCAT.Core.ChunkedLz4.Lz4Chunk.Read(Stream inputStream) in R:\Games\Cyberpunk 2077\CyberCAT\CyberCAT.Core\Classes\Lz4Chunk.cs:line 40
   at CyberCAT.Core.Classes.CyberPunkSaveFile.Decompress(Stream input) in R:\Games\Cyberpunk 2077\CyberCAT\CyberCAT.Core\Classes\CyberPunkSaveFile.cs:line 65
   at CyberCAT.Forms.Form1.uncompressButton_Click(Object sender, EventArgs e) in R:\Games\Cyberpunk 2077\CyberCAT\CyberCAT.Forms\Form1.cs:line 38
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at CyberCAT.Forms.Program.Main() in R:\Games\Cyberpunk 2077\CyberCAT\CyberCAT.Forms\Program.cs:line 19
   ```

**Comment by SirBitesalot** [comment]
Fixed by 2c283b3
